### ISSUE TITLE
Make entities evaluate by data flow

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/llhd-sim#6]
At the moment entities are treated like processes and instructions are evaluated in sequence. This breaks the semantics of an entity in that `drv` instructions get re-evaluated whenever *anything* in the entity changes, quickly causing infinite simulation cycles. An entity should rather have a set of "dirty" instructions (initially set to the `prb` instructions operating on changed signals). Instructions are removed from the set and executed, and if their output value changes, all dependent instructions are inserted into the set.

### Todo
- [x] Add a `dirty` set of instructions to entity evaluation.
- [x] Initialize the dirty set with the `prb` instructions that operate on changed signals (alternatively on *all* instructions for now).
- [x] Iteratively pop instructions off the dirty set.
- [x] Evaluate the instruction; if its result value changes, add all uses to the dirty set.
